trigger: none
pr: none

resources:
  pipelines:
  - pipeline: pipelineTrigger
    source: GitHubTemplates
    trigger: 
      branches:
      - master

stages:
- stage:
  pool:
    vmImage: 'ubuntu-latest'
  jobs:
  - deployment: DeployQA
    environment: Dep-QA
    strategy:
      runOnce:
        deploy:
          steps:
          - script: echo Deploying the code!
  # Doing a "ping" verification after the deploy since we don't have real tests
  - job: TestQA
    displayName: Verify deployment
    dependsOn: DeployQA
    steps:
      - script: curl https://$(Agent.MachineName)/SomeVirtualRoot/SomeHealthCheck

- stage:
  pool:
    vmImage: 'ubuntu-latest'
  jobs:
  - deployment: DeployProduction
    environment: Dep-Prod
    strategy:
      runOnce:
        deploy:
          steps:
          - script: echo Deploying the code to production!
