resources:
  pipelines:
  - pipeline: pipelineTrigger
    source: GitHubTemplates 
    trigger: 
      branches:
      - releases/*
      - master

stages:
- stage:
  pool:
    vmImage: 'ubuntu-latest'
  jobs:
  - deployment: DeployQA
    environment: Dep-QA
    strategy:
      runOnce:
        deploy:
          steps:
          - script: echo Deploying the code!

- stage:
  pool:
    vmImage: 'ubuntu-latest'
  jobs:
  - deployment: DeployProduction
    environment: Dep-Prod
    strategy:
      runOnce:
        deploy:
          steps:
          - script: echo Deploying the code to production!
