trigger:
- master
pr:
- none

resources:
  repositories:
    - repository: templateRepo
      type: github
      endpoint: gitHubEndpoint
      name: dmckinstry/PipelineTemplates

pool:
  vmImage: 'ubuntu-16.04'

extends:
  template: extends/template.yml@templateRepo
  parameters:
    buildSteps:
      - script: echo Compiling my code
        displayName: Compile
      - script: echo Testing my code
        displayName: Test
      - script: echo Package my code
        displayName: Package
    publishArtifact: MyPackage

